/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScRouteImport } from './routes/sc'
import { Route as GaRouteImport } from './routes/ga'
import { Route as IndexRouteImport } from './routes/index'

const ScRoute = ScRouteImport.update({
  id: '/sc',
  path: '/sc',
  getParentRoute: () => rootRouteImport,
} as any)
const GaRoute = GaRouteImport.update({
  id: '/ga',
  path: '/ga',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ga': typeof GaRoute
  '/sc': typeof ScRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ga': typeof GaRoute
  '/sc': typeof ScRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ga': typeof GaRoute
  '/sc': typeof ScRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ga' | '/sc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ga' | '/sc'
  id: '__root__' | '/' | '/ga' | '/sc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaRoute: typeof GaRoute
  ScRoute: typeof ScRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sc': {
      id: '/sc'
      path: '/sc'
      fullPath: '/sc'
      preLoaderRoute: typeof ScRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga': {
      id: '/ga'
      path: '/ga'
      fullPath: '/ga'
      preLoaderRoute: typeof GaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaRoute: GaRoute,
  ScRoute: ScRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
