/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScIndexRouteImport } from './routes/sc/index'
import { Route as GaIndexRouteImport } from './routes/ga/index'
import { Route as GaRcidRouteImport } from './routes/ga/$rcid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScIndexRoute = ScIndexRouteImport.update({
  id: '/sc/',
  path: '/sc/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaIndexRoute = GaIndexRouteImport.update({
  id: '/ga/',
  path: '/ga/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaRcidRoute = GaRcidRouteImport.update({
  id: '/ga/$rcid',
  path: '/ga/$rcid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ga/$rcid': typeof GaRcidRoute
  '/ga/': typeof GaIndexRoute
  '/sc/': typeof ScIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ga/$rcid': typeof GaRcidRoute
  '/ga': typeof GaIndexRoute
  '/sc': typeof ScIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ga/$rcid': typeof GaRcidRoute
  '/ga/': typeof GaIndexRoute
  '/sc/': typeof ScIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ga/$rcid' | '/ga/' | '/sc/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ga/$rcid' | '/ga' | '/sc'
  id: '__root__' | '/' | '/ga/$rcid' | '/ga/' | '/sc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaRcidRoute: typeof GaRcidRoute
  GaIndexRoute: typeof GaIndexRoute
  ScIndexRoute: typeof ScIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sc/': {
      id: '/sc/'
      path: '/sc'
      fullPath: '/sc/'
      preLoaderRoute: typeof ScIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/': {
      id: '/ga/'
      path: '/ga'
      fullPath: '/ga/'
      preLoaderRoute: typeof GaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga/$rcid': {
      id: '/ga/$rcid'
      path: '/ga/$rcid'
      fullPath: '/ga/$rcid'
      preLoaderRoute: typeof GaRcidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaRcidRoute: GaRcidRoute,
  GaIndexRoute: GaIndexRoute,
  ScIndexRoute: ScIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
